import Foundation

enum Images {
    
    // MARK: - Static Properties
    
    static let drivenDay = "drivenDay"
    static let drivenDaySplash = "drivenDaySplash"
    static let splashBackground = "splashBackground"
    static let inactiveEmailIcon = "inactiveEmailIcon"
    static let activeEmailIcon = "activeEmailIcon"
    static let inactiveLockIcon = "inactiveLockIcon"
    static let activeLockIcon = "activeLockIcon"
    static let openedEyeIcon = "openedEyeIcon"
    static let closedEyeIcon = "closedEyeIcon"
    static let nameActiveIcon = "nameActiveIcon"
    static let nameInactiveIcon = "nameInactiveIcon"
    static let inactiveCalendarIcon = "inactiveCalendarIcon"
    static let activeCalendarIcon = "activeCalendarIcon"
    static let homeIcon = "homeIcon"
    static let whiteArrow = "whiteArrow"
    static let categoriesArrow = "categoriesArrow"
    static let downArrow = "downArrow"
    static let plus = "plus"
    static let quoteBackground = "quoteBackground"
    static let settingButtonsArrow = "settingButtonsArrow"
    static let unselectedCategory = "unselectedCategory"
    static let selectedCategory = "selectedCategory"
    static let iCalendar = "iCalendar"
    static let googleCalendar = "googleCalendar"
    static let emptyRectangle = "emptyRectangle"
    static let checkbox = "checkbox"
    static let checkboxSVG = "checkboxSVG"
    static let blueTickedIcon = "blueTickedIcon"
    static let personsIcon = "personsIcon"
    static let taskListingChecked = "taskListingChecked"
    static let taskListingUnchecked = "taskListingUnchecked"
    static let deleteIcon = "deleteIcon"
    static let crossForTable = "crossForTable"
    static let attachmentCross = "attachmentCross"
    static let tickIcon = "tickIcon"
    static let shareIcon = "shareIcon"
    static let emptyProfile = "emptyProfile"
    static let sunIcon = "sunIcon"
    static let profile = "profile"
    static let pdf = "pdf"
    static let txt = "txt"
    static let docx = "docx"
    static let ppt = "ppt"
    static let xls = "xls"
}
